wandb_version: 1

_wandb:
  desc: null
  value:
    cli_version: 0.10.31
    framework: lightgbm
    is_jupyter_run: true
    is_kaggle_kernel: false
    python_version: 3.7.10
    t:
      1:
      - 5
      - 6
      - 7
      - 8
      4: 3.7.10
      5: 0.10.31
      8:
      - 1
      - 5
    visualize:
      comparison_baseline:
        panel_config:
          fieldSettings:
            label: model
            value: rmse
          panelDefId: wandb/bar/v0
          stringSettings:
            title: Comparison baseline models
          transform:
            name: tableWithLeafColNames
          userQuery:
            queryFields:
            - args:
              - name: runSets
                value: ${runSets}
              fields:
              - fields: []
                name: id
              - fields: []
                name: name
              - fields: []
                name: _defaultColorIndex
              - args:
                - name: tableKey
                  value: comparison_baseline_table
                fields: []
                name: summaryTable
              name: runSets
        panel_type: Vega2
